In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [7]:
wildFire_df = pd.read_csv('Wild_Fire.csv')
wildFire_df

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EPISODE_ID,CZ_FIPS,WFO,END_LOCATION
0,5549398,VENTURA CO.,FILLMORE,4/28/1996,1400.0,2030635,111,LOX,FILLMORE
1,5549399,RIVERSIDE CO.,RUBIDOUX,4/29/1996,900.0,2030636,65,LOX,RUBIDOUX
2,5545326,VENTURA CO.,FILLMORE,5/1/1996,0.0,2032515,111,LOX,FILLMORE
3,5545327,RIVERSIDE CO.,RIVERSIDE,5/11/1996,1600.0,2032516,65,LOX,RIVERSIDE
4,5575790,CALAVERAS CO.,T-C RANGER UNIT,8/12/1996,NaN,2055490,9,STO,T-C RANGER UNIT
...,...,...,...,...,...,...,...,...,...
495,5336552,SAN BERNARDINO CO.,HESPERIA,11/1/2003,0.0,1163928,71,SGX,LAKE ARROWHEAD
496,5335139,RIVERSIDE CO.,RANCHO CALIFORNIA,11/1/2003,0.0,1163930,65,SGX,RANCHO CALIFORNIA
497,5335140,SAN DIEGO CO.,ESCONDIDO,11/1/2003,0.0,1163931,73,SGX,VALLEY CENTER
498,5336553,SAN DIEGO CO.,MIRAMAR,11/1/2003,0.0,1163929,73,SGX,RAMONA
499,5393393,SAN BERNARDINO COUNTY MOUNTAINS (ZONE),,3/25/2004,1330.0,1168731,55,SGX,

In [29]:
wildFire_df['CZ_FIPS'].value_counts(normalize=True).iloc[:5]

73     0.208
65     0.192
71     0.180
107    0.056
29     0.054
Name: CZ_FIPS, dtype: float64